#ifndef ANDROID_PROPERTIES_HEADER_INCLUDED
#define ANDROID_PROPERTIES_HEADER_INCLUDED

#include "mmlICString.h"

typedef enum
{
	ANDROID_PROPERTY_SERIALNO,
	ANDROID_PROPERTY_MODEL,
	ANDROID_PROPERTY_CPU,
	ANDROID_PROPERTY_DEVICE,
	ANDROID_PROPERTY_MANUFACTURER,
	ANDROID_PROPERTY_RELEASE,
	ANDROID_PROPERTY_SDK,
	ANDROID_PROPERTY_HARDWARE,
	ANDROID_PROPERTY_IMEI,
	ANDROID_PROPERTY_ID,
	ANDROID_PROPERTY_CARRIER,
	ANDROID_PROPERTY_MCCMNC
}ANDROID_PROPERTY_T;


mmlBool android_property_get(const ANDROID_PROPERTY_T prop, mmlICString ** value );

#endif //ANDROID_PROPERTIES_HEADER_INCLUDED
