#ifndef MML_STREAM_SERVER_SSL_HEADER_INCLUDED
#define MML_STREAM_SERVER_SSL_HEADER_INCLUDED

#include "mmlIStream.h"

#define MML_NETWORK_STREAM_SERVER_SSL_UUID { 0xC4713072, 0x6C00, 0x1014, 0x9653 , { 0x96, 0x05, 0x50, 0xAC, 0x57, 0x30 } }

class mmlINetworkStreamServerSSL : public mmlIStreamServer
{
	MML_OBJECT_UUID_DECL(MML_NETWORK_STREAM_SERVER_SSL_UUID)
};

#endif //MML_TCP_SERVER_SSL_HEADER_INCLUDED
