#ifndef MML_GZIP_OUTPUT_STREAM_HEADER_OUTCLUDED
#define MML_GZIP_OUTPUT_STREAM_HEADER_OUTCLUDED

#include "mmlIStream.h"

#define MML_GZIP_OUTPUT_STREAM_UUID { 0x863147DD, 0x6BF5, 0x1014, 0x8C5A , { 0xD1, 0xF7, 0x52, 0xB6, 0x75, 0x2A } }

class mmlIGZIPOutputStream : public mmlIOutputStream
{
	MML_OBJECT_UUID_DECL(MML_GZIP_OUTPUT_STREAM_UUID)
};

#endif //MML_GZIP_OUTPUT_STREAM_HEADER_OUTCLUDED